---
title: "Exploratory Data Analysis"
author: "Paul Nguyen & David Herrero Quevedo"
date: "11/13/2019"
output: pdf_document
---

```{r, message = FALSE, cache = TRUE}
#load libraries and data
library(ggplot2)
library(dplyr)
library(nbastatR)
library(tidyr)
library(tidyverse)

rotys_table <- bref_awards("Rookie of the Year")
allnbateams <- all_nba_teams(return_message = TRUE) %>%
  select(yearSeason, namePlayer, groupPosition)
  
```


```{r, cache = T}
#summary stats for starters, grouped by year and position
#not using games started, since did not keep track of before 1980
thirtygameplayersummary <- bref_players_stats(seasons = 1955:2020,
                                  tables = c("per_game")) %>%
  filter(countGames >= 30) %>%
  group_by(yearSeason, groupPosition) %>%
  summarize(meanFGPct = mean(pctFG),
            mean3FGPct = mean(pctFG3),
            meanFGM = mean(fgmPerGame),
            meanFGA = mean(fgaPerGame),
            mean3FGM = mean(fg3mPerGame),
            mean3FGA = mean(fg3aPerGame),
            meanFTA = mean(ftaPerGame),
            meanFTM = mean(ftmPerGame),
            meanORB = mean(orbPerGame),
            meanDRB = mean(drbPerGame),
            meanAST = mean(astPerGame),
            meanSTL = mean(stlPerGame),
            meanBLK = mean(blkPerGame),
            meanTOV = mean(tovPerGame),
            meanPTS = mean(ptsPerGame))
#some graphs 
#fg pct
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGPct, color = groupPosition)) +
  geom_line()
#3FGPct, see the introduction of 3 point line
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGPct, color = groupPosition)) +
  geom_line()
#meanFGM
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGM, color = groupPosition)) +
  geom_line()
#meanFGA
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGA, color = groupPosition)) +
  geom_line()
#mean3FGM this one seems pretty important
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGM, color = groupPosition)) +
  geom_line()
#mean3FGAthis one seems pretty important
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGA, color = groupPosition)) +
  geom_line()
#meanFTA
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFTA, color = groupPosition)) +
  geom_line()
#meanFTM
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFTM, color = groupPosition)) +
  geom_line()
#meanORB
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanORB, color = groupPosition)) +
  geom_line()
#meanDRB
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanDRB, color = groupPosition)) +
  geom_line()
#meanAST
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanAST, color = groupPosition)) +
  geom_line()
#meanSTL
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanSTL, color = groupPosition)) +
  geom_line()
#meanBLK
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanBLK, color = groupPosition)) +
  geom_line()
#meanTOV
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanTOV, color = groupPosition)) +
  geom_line()
#meanPTS
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanPTS, color = groupPosition)) +
  geom_line()
```


```{r, message = F, cache = T}
#made a new chunk for our "final" dataset
players <- bref_players_stats(seasons = 1950:2020, tables = c("advanced", "per_game"), include_all_nba = TRUE)

players_post1984 <- filter(players, yearSeason >= 1984) %>%
  filter(countGames > 29)

#getting rid of some not useful variables
drops <- c("slugSeason", "idPlayerNBA", "namePlayerBREF", 
           "slugPlayerBREF", "urlPlayerThumbnail", "urlPlayerHeadshot",
           "urlPlayerPhoto", "urlPlayerStats", "urlPlayerActionPhoto",
           "isSeasonCurrent","slugPlayerSeason")

players_post1984 <-
  players_post1984[,!(names(players_post1984) %in% drops)]

#some summary statistics
summarystatistics1984 <- players_post1984 %>%
  summarize(meanpctFTRate = mean(pctFTRate),
            meanpct3PRate = mean(pct3PRate),
            meanpctFG = mean(pctFG),
            meanpctFG3 = mean(pctFG3),
            meanpctFG2 = mean(pctFG2),
            meanpctEFG = mean(pctEFG),
            meanpctFT = mean(pctFT),
            meanfgmPerGame = mean(fgmPerGame),
            meanfgaPerGame = mean(fgaPerGame),
            meanfg3mPerGame = mean(fg3mPerGame),
            meanfg3aPerGame = mean(fg3aPerGame),
            meanfg2mPerGame = mean(fg2mPerGame),
            meanfg2aPerGame = mean(fg2aPerGame),
            meanftmPerGame = mean(ftmPerGame),
            meanftaPerGame = mean(ftaPerGame),
            meanptsPerGame = mean(ptsPerGame),
            meanpctORB = mean(pctORB),
            meanpctTRB = mean(pctTRB),
            meanpctDRB = mean(pctDRB),
            meanorbPerGame = mean(orbPerGame),
            meandrbPerGame = mean (drbPerGame),
            meantrbPerGame = mean(trbPerGame),
            meanpctSTL = mean(pctSTL),
            meanpctBLK = mean(pctBLK),
            meanstlPerGame = mean(stlPerGame),
            meanblkPerGame = mean(blkPerGame),
            meanpfPerGame = mean(pfPerGame),
            meanratioOWS = mean(ratioOWS),
            meanratioDWS = mean(ratioDWS),
            meanratioWS = mean(ratioWS),
            meanratioWSPer48 = mean(ratioWSPer48),
            meanratioOBPM = mean(ratioOBPM),
            meanratioDBPM = mean(ratioDBPM),
            meanratioBPM = mean(ratioBPM),
            meanratioVORP = mean(ratioVORP),
            sdpctFTRate = sd(pctFTRate),
            sdpct3PRate = sd(pct3PRate),
            sdpctFG = sd(pctFG),
            sdpctFG3 = sd(pctFG3),
            sdpctFG2 = sd(pctFG2),
            sdpctEFG = sd(pctEFG),
            sdpctFT = sd(pctFT),
            sdfgmPerGame = sd(fgmPerGame),
            sdfgaPerGame = sd(fgaPerGame),
            sdfg3mPerGame = sd(fg3mPerGame),
            sdfg3aPerGame = sd(fg3aPerGame),
            sdfg2mPerGame = sd(fg2mPerGame),
            sdfg2aPerGame = sd(fg2aPerGame),
            sdftmPerGame = sd(ftmPerGame),
            sdftaPerGame = sd(ftaPerGame),
            sdptsPerGame = sd(ptsPerGame),
            sdpctORB = sd(pctORB),
            sdpctTRB = sd(pctTRB),
            sdpctDRB = sd(pctDRB),
            sdorbPerGame = sd(orbPerGame),
            sddrbPerGame = sd (drbPerGame),
            sdtrbPerGame = sd(trbPerGame),
            sdpctSTL = sd(pctSTL),
            sdpctBLK = sd(pctBLK),
            sdstlPerGame = sd(stlPerGame),
            sdblkPerGame = sd(blkPerGame),
            sdpfPerGame = sd(pfPerGame),
            sdratioOWS = sd(ratioOWS),
            sdratioDWS = sd(ratioDWS),
            sdratioWS = sd(ratioWS),
            sdratioWSPer48 = sd(ratioWSPer48),
            sdratioOBPM = sd(ratioOBPM),
            sdratioDBPM = sd(ratioDBPM),
            sdratioBPM = sd(ratioBPM),
            sdratioVORP = sd(ratioVORP)
            )
summarystatistics1984


#trying to standardize
#standardizedplayers1984nostat <- players_post1984[,-c(11:31, 34:50)]


#standardizedplayers1984stats <-
 # players_post1984[,c(11:31, 34:50)] %>%
  #scale() 
  
#standardizedplayers1984 <- 
 # cbind(c(standardizedplayers1984nostat,standardizedplayers1984stats)) 

#standardizedplayers1984 <- 
 # as.data.frame(as.table(standardizedplayers1984))


```


```{r, message = F, cache = T}
players <- bref_players_stats(seasons = 1950:2020, tables = c("advanced", "per_game"), include_all_nba = TRUE)
players_all_nbas <- filter(players, isAllNBA == TRUE)
players_fifties <- filter(players, yearSeason < 1960)
players_sixties <- filter(players, yearSeason >= 1960 & yearSeason < 1970)
players_seventies <- filter(players, yearSeason >= 1970 & yearSeason < 1980)
players_eighties <- filter(players, yearSeason >= 1980 & yearSeason < 1990)
players_nineties <- filter(players, yearSeason >= 1990 & yearSeason < 2000)
players_twothousands <- filter(players, yearSeason >= 2000 & yearSeason < 2010)
players_twentytens <- filter(players, yearSeason >= 2010 & yearSeason < 2020)


players_post1984 <- filter(players, yearSeason >= 1984) %>%
  filter(countGames > 29)

#getting rid of some not useful variables
drops <- c("slugSeason", "idPlayerNBA", "namePlayerBREF", 
           "slugPlayerBREF", "urlPlayerThumbnail", "urlPlayerHeadshot",
           "urlPlayerPhoto", "urlPlayerStats", "urlPlayerActionPhoto",
           "isSeasonCurrent","slugPlayerSeason")

players_post1984 <-
  players_post1984[,!(names(players_post1984) %in% drops)]



allnbasummary <- all_nbas_withstats %>%
  group_by(yearSeason, groupPosition) %>%
  summarize(meanFGPct = mean(pctFG),
            mean3FGPct = mean(pctFG3),
            meanFGM = mean(fgmPerGame),
            meanFGA = mean(fgaPerGame),
            mean3FGM = mean(fg3mPerGame),
            mean3FGA = mean(fg3aPerGame),
            meanFTA = mean(ftaPerGame),
            meanFTM = mean(ftmPerGame),
            meanORB = mean(orbPerGame),
            meanDRB = mean(drbPerGame),
            meanAST = mean(astPerGame),
            meanSTL = mean(stlPerGame),
            meanBLK = mean(blkPerGame),
            meanTOV = mean(tovPerGame),
            meanPTS = mean(ptsPerGame))
#graphs for all-nba teams
#fg pct
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGPct, color = groupPosition)) +
  geom_line()
#3FGPct, see the introduction of 3 point line
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGPct, color = groupPosition)) +
  geom_line()
#meanFGM
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGM, color = groupPosition)) +
  geom_line()
#meanFGA
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFGA, color = groupPosition)) +
  geom_line()
#mean3FGM this one seems pretty important
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGM, color = groupPosition)) +
  geom_line()
#mean3FGAthis one seems pretty important
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = mean3FGA, color = groupPosition)) +
  geom_line()
#meanFTA
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFTA, color = groupPosition)) +
  geom_line()
#meanFTM
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanFTM, color = groupPosition)) +
  geom_line()
#meanORB
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanORB, color = groupPosition)) +
  geom_line()
#meanDRB
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanDRB, color = groupPosition)) +
  geom_line()
#meanAST
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanAST, color = groupPosition)) +
  geom_line()
#meanSTL
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanSTL, color = groupPosition)) +
  geom_line()
#meanBLK
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanBLK, color = groupPosition)) +
  geom_line()
#meanTOV
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanTOV, color = groupPosition)) +
  geom_line()
#meanPTS
ggplot(data = thirtygameplayersummary, 
       mapping = aes(x = yearSeason, y = meanPTS, color = groupPosition)) +
  geom_line()
```